'use-client'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../component/header'
import Footer from '../component/footer'
import { ReduxProvider } from '../@core/redux/provider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import login from '../component/authentication/login'
import { JSX } from 'react'
import { useDispatch } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })




export const metadata: Metadata = {
  title: 'Online clothing shop',
  description: 'Generated by create next app',
}


export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
  }) {
  
  
  if (typeof window !== 'undefined') {
    const storedUserString = localStorage.getItem('user');
    const storedUser = storedUserString ? JSON.parse(storedUserString) : null
  }
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ToastContainer />
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}

function dispatch(arg0: JSX.Element) {
  throw new Error('Function not implemented.')
}

